API_TOKEN = ''
MAX_TOKENS_IN_TASK = 300
MAX_TOKENS_IN_ANSWER = 100
ENDPOINT = 'http://localhost:1234/v1/chat/completions'
HEADER = {"Content-Type": "application/json"}
IAM_TOKEN = ("")
FOLDER_ID = ""
COUNT_SESSION = 3
TOKENS_IN_SESSION = 400
TEMPERATURE = 0.7
